
version: '2'

networks:
  basic:

services:

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
# =======================CHANGED==================
  peer0.Operator.example.com:
    container_name: peer0.Operator.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      #------------change---------------
      - CORE_PEER_ID=peer0.Operator.example.com
      - CORE_PEER_ADDRESS=peer0.Operator.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Operator.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Operator.example.com:7051
      - CORE_PEER_LOCALMSPID=OperatorMSP
    volumes:
      #------------change--------
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/Operator.example.com/peers/peer0.Operator.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/Operator.example.com/peers/peer0.Operator.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  peer0.Supplier.example.com:
    container_name: peer0.Supplier.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Supplier.example.com
      - CORE_PEER_ADDRESS=peer0.Supplier.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Supplier.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Supplier.example.com:7051
      - CORE_PEER_LOCALMSPID=SupplierMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/Supplier.example.com/peers/peer0.Supplier.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/Supplier.example.com/peers/peer0.Supplier.example.com/tls:/etc/hyperledger/fabric/tls

    ports:
      - 8051:7051
      - 8053:7053

  peer0.Distributor.example.com:
    container_name: peer0.Distributor.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Distributor.example.com
      - CORE_PEER_ADDRESS=peer0.Distributor.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Distributor.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Distributor.example.com:7051
      - CORE_PEER_LOCALMSPID=DistributorMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/Distributor.example.com/peers/peer0.Distributor.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/Distributor.example.com/peers/peer0.Distributor.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

  peer0.Retailer.example.com:
    container_name: peer0.Retailer.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Retailer.example.com
      - CORE_PEER_ADDRESS=peer0.Retailer.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Retailer.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.Retailer.example.com:7051
      - CORE_PEER_LOCALMSPID=RetailerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/Retailer.example.com/peers/peer0.Retailer.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/Retailer.example.com/peers/peer0.Retailer.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 6051:7051
      - 6053:7053


  # cli:
  #   container_name: cli
  #   image: hyperledger/fabric-tools
  #   tty: true
  #   environment:
  #     - GOPATH=/opt/gopath
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     - CORE_LOGGING_LEVEL=info
  #     - CORE_PEER_ID=cli
  #     - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
  #     - CORE_PEER_LOCALMSPID=Org1MSP
  #     - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
  #     - CORE_CHAINCODE_KEEPALIVE=10
  #   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  #   command: /bin/bash
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - ./../chaincode/:/opt/gopath/src/github.com/
  #       - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
  #   networks:
  #       - basic
  #   #depends_on:
    #  - orderer.example.com
    #  - peer0.org1.example.com
    #  - couchdb  
     cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      # ---CHANGED--- peer0 from Org1 is the default for this CLI container
      - CORE_PEER_ADDRESS=peer0.Operator.example.com:7051
      - CORE_PEER_LOCALMSPID=OperatorMSP
      - CORE_PEER_TLS_ENABLED=true
      # ---CHANGED--- changed to reflect peer0 name, org1 name and our company's domain
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Operator.example.com/peers/peer0.Operator.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Operator.example.com/peers/peer0.Operator.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Operator.example.com/peers/peer0.Operator.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Operator.example.com/users/Admin@Operator.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # ---CHANGED--- command needs to be connected out as we will be issuing commands explicitly, not using by any script
    # command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
                # ---CHANGED--- chaincode path adjusted
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
             # ---CHANGED--- reference to our orderer
      - orderer.example.com
      - peer0.Operator.example.com
      - peer0.Supplier.example.com
      - peer0.Distributor.example.com
      - peer0.Retailer.example.com
    networks:
      - basic
