# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

# ---CHANGED--- our network is called "basic"
networks:
  basic:

services:

  orderer.example.com:
    extends:
      file:   docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    #--------change---------
    networks:
      - basic

  peer0.Operator.example.com:
    container_name: peer0.Operator.example.com
    extends:
      file:  docker-compose-base.yaml
      service: peer0.Operator.example.com
    networks:
      - basic

  peer0.Supplier.example.com:
    container_name: peer0.Supplier.example.com
    extends:
      file:  docker-compose-base.yaml
      service: peer0.Supplier.example.com
    networks:
      - basic

  peer0.Distributor.example.com:
    container_name: peer0.Distributor.example.com
    extends:
      file:  docker-compose-base.yaml
      service: peer0.Distributor.example.com
    networks:
      - basic

  peer0.Retailer.example.com:
    container_name: peer0.Retailer.example.com
    extends:
      file:  docker-compose-base.yaml
      service: peer0.Retailer.example.com
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      # ---CHANGED--- peer0 from Org1 is the default for this CLI container
      - CORE_PEER_ADDRESS=peer0.Operator.example.com:7051
      - CORE_PEER_LOCALMSPID=OperatorMSP
      - CORE_PEER_TLS_ENABLED=true
      # ---CHANGED--- changed to reflect peer0 name, org1 name and our company's domain
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Operator.example.com/peers/peer0.Operator.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Operator.example.com/peers/peer0.Operator.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Operator.example.com/peers/peer0.Operator.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Operator.example.com/users/Admin@Operator.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # ---CHANGED--- command needs to be connected out as we will be issuing commands explicitly, not using by any script
    # command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
                # ---CHANGED--- chaincode path adjusted
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
             # ---CHANGED--- reference to our orderer
      - orderer.example.com
      - peer0.Operator.example.com
      - peer0.Supplier.example.com
      - peer0.Distributor.example.com
      - peer0.Retailer.example.com
    networks:
      - basic
